spring:
  application:
    name: sistemaBD
  datasource:
    url: jdbc:postgresql://myprojects-concurrent1.k.aivencloud.com:20448/taller_proyecto
    username: avnadmin
    password: ${AIVEN_DB_PASSWORD}
  jpa:
    hibernate:
      # Desactiva el DDL de Hibernate para evitar conflictos
      ddl-auto: update
  flyway:
    # Deshabilita el auto-config de Flyway
    enabled: false
    # Ejecuta el baseline al iniciar, si la tabla de historial aún no existe
    baseline-on-migrate: false
    # Le dice a Flyway qué versión existente debe considerar como la base (V1 por defecto)
    baseline-version: 1