spring:
  profiles:
    active: local
  application:
    name: sistemaBD
  jpa:
    hibernate:
      # Valida el esquema de la base de datos contra las entidades JPA al iniciar
      ddl-auto: validate
  liquibase:
    # Habilita la integración de Liquibase con Spring Boot
    enabled: true
    # Ruta al archivo de changelog principal
    change-log: classpath:db/changelog/db.changelog-master.xml